### ISSUE TITLE
Move the CSV data to GitHub

### ISSUE THREAD

**Issue by denbonte** [AIM-Harvard/foundation-cancer-image-biomarker#237]
## 🚀 Feature Request

Move the CSV data from Dropbox to Github.

Since I understand this might not be the best repo to do so, I would be happy to host them in the `idc-radiomics-reproducibility` repo, e.g., as done for Hosny et Al [here](https://github.com/ImagingDataCommons/idc-radiomics-reproducibility/tree/main/data) (I could have pulled them straight away, but I wanted to ask before doing so 🙃).

## 🔈 Motivation

I think this makes the tabled data more accessible (e.g., they can be inspected in an easier way, they can be versioned, and so on) and makes it possible to have them part of a release (e.g., a Zenodo release) - since they are valuable data to add to the NSCLC-Radiomics and the NSCLC-Radiogenomics collections, in my opinion.

**Comment by surajpaib** [comment]
Absolutely! Feel free to go ahead and put them on the GitHub repo, we can also provide a link between the two as you see fit

**Comment by surajpaib** [comment]
I will replace the notebooks on this README with the ones from you once you let me know they are ready!

**Comment by denbonte** [comment]
Added everything in the last couple of commits (https://github.com/ImagingDataCommons/idc-radiomics-reproducibility/commit/434b547cf2d51df2436ae47fed5f94eea263a49e and https://github.com/ImagingDataCommons/idc-radiomics-reproducibility/commit/0d2a7650b7ff39618c6ff003f41d964e795487b8).

Works perfect. I'm going to push the notebook to the repo in a few minutes.
