### ISSUE TITLE
11,467 is voumes or patches?

### ISSUE THREAD

**Issue by gaohailiang520** [AIM-Harvard/foundation-cancer-image-biomarker#296]
Thank you for your great work. i want to ask that you say "11,467 unlabelled lesions for contrastive training", is that mean 11,467 voumes or patches？

**Comment by 1170300714** [comment]
Hello, I would like to know whether "11,467 unlabelled lesions" refers to 11,467 original 3D CT volumes (for example, complete thoracic and abdominal CT images.), or to 11,467 3D patches whether containing lesions or not, that have been cropped from the original volumes?
