### ISSUE TITLE
AssertionError: Invalid coordinates: min_d >= max_d

### ISSUE THREAD

**Issue by wafaequo** [AIM-Harvard/foundation-cancer-image-biomarker#300]
I downloaded the SPIE-AAPM Lung CT Challenge data and converted the images from DICOM to nii using the following code: https://github.com/rordenlab/dcm2niix.

The coordinates of the nodule are given in pixels and I converted it to physical coordinate space using .get_zooms() from the metadata of each image.

I still keep getting the following errors (depending on the image I choose) when running visualize_seed_point:
AssertionError: Invalid coordinates: min_d >= max_d
AssertionError: Invalid coordinates: min_h >= max_h

What am I doing wrong?

**Comment by surajpaib** [comment]
Hi @wafaequo 

I'm not very familiar with nibabel as I mostly use SimpleITK for my image loading purposes. I'm assuming there might be a mismatch between the orientation provided by nibabel coordinates and the ones expected by FMCIB. 


Could you test the same workflow with SimpleITK and let me know if it works?

```python

import SimpleITK as sitk

# Load the image
image_path = 'path/to/your/image.nii'  # Replace with your image file path
image = sitk.ReadImage(image_path)

# Convert image coordinates (i, j, k) to physical coordinates (x, y, z)
def image_to_physical(image_coords):
    return image.TransformIndexToPhysicalPoint(image_coords)

# Example image coordinates
image_coords = (100, 150, 75) 

# Convert to physical coordinates
physical_coords = image_to_physical(image_coords)
print(f"Physical coordinates: {physical_coords}")



```

**Comment by surajpaib** [comment]
Alternatively, if you can share a image coordinate, the image itself and your current physical coordinate, I can test it myself and let you know how to modify.

**Comment by yuvfried** [comment]
@surajpaib

I need clarification on the **coordinate system** expected by your model's functions.

Specifically, should I transform my current **RAS** annotations to **LPS** before passing them?

Given that I am satisfied with the output of `visualize_seed_point` when using a row from my CSV:

1.  Does this guarantee that the `coordX`, `coordY`, and `coordZ` values are correctly **aligned with my NIfTI file specified in `image_path`?
2.  Can I confidently pass this same CSV data directly to the `get_features` function without any further coordinate transformation?

Thanks for your help!
