### ISSUE TITLE
How to generate valid CSV file while sing my own data

### ISSUE THREAD

**Issue by Dtdavidgit** [AIM-Harvard/foundation-cancer-image-biomarker#303]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/foundation_image_biomarker/foundation-image-biomarker/issues?q=is%3Aissue).

## ❓ Question

Hi there, I would like to use your wonderful tool on my test data, however, I noticed that your example csv has 1 set of coordinate (x,y,z) for 1 patient (nifti file).

However, I extracted the coordinate from my data which done segmentation by other tool, there are multiple sets of X,Y,Z.

Could you please let me know which kind of coordinates you are using?

**Comment by surajpaib** [comment]
Hi @Dtdavidgit 

Thanks for your interest. 

You could provide multiple sets of coordinates in the CSV as well - by simply listing them as multiple rows.

In our study, we used coordinates from several lesions (multiple points per patient/scan) as well as primary tumors specifically - depending on the use-case of relevance. 

Each coordinate will be used independently in the feature extraction process and it would be upto you on how you can aggregate these. Operations on the features are also possible such as taking the average feature value across multiple points or taking variance estimates between features in a single scan. Very use-case dependent I'd reckon.
