### ISSUE TITLE
about ‘’lighter fit‘’

### ISSUE THREAD

**Issue by Devil-Ideal** [AIM-Harvard/foundation-cancer-image-biomarker#304]
Hi ! I would like to understand more about the command lighter fit --config_file ./experiments/adaptation/fmcib_finetune.yaml . Could you please point me to the relevant Python script or module that is associated with the lighter fit command?

**Comment by Devil-Ideal** [comment]
Still I would like to confirm whether Use Case 1, "Lesion anatomical site classification," is an 8-class task. Specifically, are the classes as follows?

Bone
Abdomen
Mediastinum
Liver
Lung
Kidney
Soft tissue
Pelvis

**Comment by surajpaib** [comment]
Hi @Devil-Ideal 
The `lighter fit` command is from the lighter framework here: https://github.com/project-lighter/lighter

I recommend reading the docs from the framework - it is largely based off Pytorch Lightning. If you have any further questions, let us know!

For the use-case 1, indeed, those are the classes.

**Comment by Devil-Ideal** [comment]
> Hi @Devil-Ideal The `lighter fit` command is from the lighter framework here: https://github.com/project-lighter/lighter
> 
> I recommend reading the docs from the framework - it is largely based off Pytorch Lightning. If you have any further questions, let us know!
> 
> For the use-case 1, indeed, those are the classes.

thank you
